Repository robocorp/robocorp, pull requests merged in 2024-04, with the labels that each got.

#324 Add sentinel class to generate consistent docs
  devutils/src/devutils/invoke_utils.py
  windows/docs/CHANGELOG.md
  windows/docs/api/robocorp.windows.md
  windows/poetry.lock
  windows/src/robocorp/windows/_control_element.py
Labels: Chore / Tech Debt

#322 Verify if there is an action-server newer version
  action_server/go-wrapper/go.mod
  action_server/go-wrapper/go.sum
  action_server/go-wrapper/main.go
  action_server/poetry.lock
  action_server/pyproject.toml
  action_server/src/robocorp/action_server/cli.py
  action_server/tasks.py
Labels: Improvement, Feature, Action Server

#334 Fixing the current CVE issues
  action_server/frontend/package-lock.json
  action_server/frontend/package.json
  devutils/requirements.txt
  log/output-react/package-lock.json
  log/output-react/package.json
Labels: dependencies, Chore / Tech Debt
