Repository robocorp/robocorp, pull requests merged in 2024-01, with the labels that each got.

#120 First 3rd party library doc
  docs/3rd_party/README.md
  docs/3rd_party/requests/README.md
  docs/3rd_party/requests/snippets/download.py
  docs/README.md
Labels: documentation

#141 Remove `http` package in favor to `requests`
  http/docs/CHANGELOG.md
  http/docs/api/.pages
  http/docs/api/README.md
  http/docs/api/robocorp.http.md
  http/poetry.lock
  http/pyproject.toml
  http/src/robocorp/http/__init__.py
  http/src/robocorp/http/_http.py
  http/tests/test_http.py
Labels: clean-up

#181 Filter endpoints from Action Server OpenAPI spec
  action_server/src/robocorp/action_server/_server.py
  action_server/src/robocorp/action_server/_settings.py
  action_server/src/robocorp/action_server/cli.py
  action_server/tests/action_server_tests/test_server.py
  action_server/tests/action_server_tests/test_server/test_auth_routes.yml
  action_server/tests/action_server_tests/test_server/test_import.yml
  action_server/tests/action_server_tests/test_server/test_import_no_conda.txt
  action_server/tests/action_server_tests/test_server/test_routes.yml
  action_server/tests/action_server_tests/test_server/test_schema_request_no_actions_registered.yml
  action_server/tests/action_server_tests/test_server/test_server_full_openapi_flag.yml
  action_server/tests/action_server_tests/test_server/test_server_url_flag.yml
Labels: enhancement, Action Server

#182 Action Server frontend dependencies update
  action_server/frontend/package-lock.json
  action_server/frontend/package.json
Labels: dependencies, Action Server

#195 Add Pandas to 3rd party library docs
  docs/3rd_party/pandas/README.md
  docs/3rd_party/pandas/snippets/export_to_csv.py
  docs/3rd_party/pandas/snippets/people.csv
  docs/3rd_party/pandas/snippets/query_csv_data.py
Labels: documentation
